### ISSUE TITLE
Fix inability to click on markers with overlapping coordinates

### ISSUE THREAD

**Issue by elk2klein** [ebgoldstein/IrmaTweets#7]
Options:
1. Jitter the coordinates
2. Spiderfier plugin is available for Leaflet through HTML - would involve "includeHTML" maybe?

**Comment by elk2klein** [comment]
Jittered the coordinates for now, may look into other option later.

**Comment by ebgoldstein** [comment]
i replaced the geoR jitter with another jitter that does not require a new library.
